using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace buisnessCase_trends3.Models
{
    public class Achievement
    {
        //class autogenerated by CoPilot
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PointValue { get; set; }

        [ForeignKey("Task")]
        public int TaskId { get; set; }

        public Task? task { get; set; }
    }
}
